# Generated by Django 3.2 on 2021-04-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_wide',
            field=models.BooleanField(default=False),
        ),
    ]
