# Generated by Django 3.2 on 2021-04-28 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210427_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment'),
        ),
    ]
