# Generated by Django 3.2 on 2021-04-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment_replied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replied',
            new_name='replied_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='top_level_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_comments', to='api.comment'),
        ),
    ]
