# Generated by Django 3.2 on 2021-05-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingamesuser',
            name='name_color',
            field=models.CharField(choices=[('#ffc6c6', 'Light red'), ('#81cdd5', 'Light blue'), ('#9bc17b', 'Light green'), ('#ffb876', 'Orange'), ('#ae81d5', 'Purple'), ('#e5b2da', 'Pink'), ('#ffce67', 'Yellow')], default='#ffc6c6', max_length=100),
        ),
    ]
