# Generated by Django 3.2 on 2021-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingamesuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Simple KinGames user'), ('MANAGER', 'Manager'), ('ADMIN', 'admin of the service')], default='USER', max_length=10),
        ),
    ]
