# Generated by Django 3.2 on 2021-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_is_wide'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_licences',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
