# Generated by Django 3.2 on 2021-04-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210428_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_licences',
            field=models.IntegerField(default=1000),
        ),
    ]
