# Generated by Django 3.2 on 2021-04-30 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_game_number_of_licences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replied_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='top_level_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_comments', to='api.comment'),
        ),
    ]
