# Generated by Django 3.2 on 2021-05-12 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_kingamesuser_name_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bought_times',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='cartgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_games', to='api.game'),
        ),
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimated_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
