# Generated by Django 3.2 on 2021-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermark',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
